spring:
  application:
    name: springToDo

  datasource:
    url: jdbc:postgresql://localhost:5432/springtodo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  messages:
    encoding: UTF-8

server:
  port: 8080
